name: Check code lints

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  container-build:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-build` executes in
    container: python:3.9.4-slim-buster
    steps:
      - uses: actions/checkout@v2

  flake8:
    needs: [container-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Falke8
        run: pip install flake8
      - name: Lint with flake8
        working-directory: time_keep_api
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --exclude .git,.idea,.pytest_cache,docker,docs,*.egg-info,migrations,conf
